stats-workshop.pdf: bayes.tex counting.tex probability.tex common-distributions.tex independence.tex random-variables.tex conditional-probability.tex introduction.tex stats-workshop.tex
	pdflatex stats-workshop.tex
